language: python

dist: xenial
   
python: "3.7"

services:
  - xvfb

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n frsystem python=$TRAVIS_PYTHON_VERSION mtcnn scikit-learn opencv
  - conda activate frsystem
  - pip install requests
  - conda install -c anaconda tensorflow
  - python setup.py install
  - conda list
script:
  - python frsapp/mask_face_recognizer.py
